### PR TITLE
fix: fixes an issue that cannot locate popover trigger if explicitly set the `isOpen` prop

### LINKED ISSUE #396: tooltip issue
tooltip can not show correctly when set defaultIsOpen true.
image

### PR DESCRIPTION
**Pull request by cheton**
Demo: https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-410/popover

See #408 for a similar issue on tooltip

## Description

The popover cannot locate the trigger if explicitly set the `isOpen` prop.

### Steps to reproduce

1. Go to https://trendmicro-frontend.github.io/tonic-ui/react/0.23.0/popover
2. Add the `isOpen` prop to a `Popover` component.
3. Inline styles are not available on the popover trigger

### Expected result

image

## What's Changed

* Use `isHydrated` state to check whether it is the initial render for SSR-friendly.
* Remove `shouldWrapChildren` prop from `PopoverTrigger`.
* You can use function as children to render the popover trigger (anchor) if you don't want it to be wrapped with a `Box` component:
  ```jsx
  <PopoverTrigger>
    {({ getPopoverTriggerProps }) => {
      return (
        <Button {...getPopoverTriggerProps()}>
          Tooltip Trigger
        </Button>
      );
    }}
  </PopoverTrigger>
  ```

  image

### CODE REVIEW

File: packages/react/src/Popover/PopoverTrigger.js [hunk 1]
```diff
@@ -67,58 +86,37 @@ const PopoverTrigger = ({
...
-        {...eventHandlerProps}
-      >
-        {children}
-      </Box>
-    );
-  }
+  const getPopoverTriggerProps = () => {
+    const popoverTriggerStyleProps = {
+      display: 'inline-block',
+      outline: '0',
```
Comment (cheton) [inline packages/react/src/Popover/PopoverTrigger.js]: remove the `outline` prop

File: packages/react/src/Popover/PopoverTrigger.js [hunk 2]
```diff
@@ -67,58 +86,37 @@ const PopoverTrigger = ({
...
+    };
 
-  const child = Children.only(children);
+    return {
+      'aria-haspopup': 'dialog',
+      'aria-expanded': isOpen,
+      'aria-controls': popoverId,
+      ref: combinedRef,
+      role: 'button',
+      tabIndex: '0',
```
Comment (cheton) [inline packages/react/src/Popover/PopoverTrigger.js]: remove the `tabIndex` attribute

File: packages/react/src/Popover/PopoverTrigger.js (hunk 1 above)
Comment (cheton) [reply packages/react/src/Popover/PopoverTrigger.js]: fixed in 0b736f45b3c9c6308e581f8fec8ee9fdfcae7b2b

File: packages/react/src/Popover/PopoverTrigger.js (hunk 2 above)
Comment (cheton) [reply packages/react/src/Popover/PopoverTrigger.js]: fixed in 0b736f45b3c9c6308e581f8fec8ee9fdfcae7b2b

**Review by tinaClin — APPROVED** [review]
