### PR TITLE
 fix(styled-system): correct handling of negative margin where `calc()` was erroneously included

### LINKED ISSUE #867: Negative margin not added properly when using `margin` shorthand
Adding negative margin to Box as `<Box margin="-10px 0 10px 0"></Box>` results in `margin: calc(10px 0 10px 0* -1);`; thus evaluating to a `Invalid Property Value`

If the same margin is divided two props as `<Box margin="0 0 10px 0" marginTop="-10px"></Box>`, it results in `margin: 0 0 10px; margin-top: calc(10px* -1);` which renders the element in expected position.

Issue is reproducible in `1.29.0` & also `v2`

### PR DESCRIPTION
**Pull request by cheton**
Check out the discussion here: https://github.com/trendmicro-frontend/tonic-ui/issues/867

### CODE REVIEW

File: packages/styled-system/src/utils/transforms.js [hunk 1]
```diff
@@ -93,16 +108,28 @@ export const positiveOrNegative = (scale, value, options) => {
    * ```
    */
   if (typeof value === 'number' && Number.isFinite(value)) {
-    const isNegative = (value < 0);
-    if (!isNegative) {
+    const absoluteValue = Math.abs(value);
+    const isNonNegative = !(value < 0);
+
+    // Return the result if the value is non-negative or if the scale object does not contain the absolute value
+    if (isNonNegative || !Object.prototype.hasOwnProperty.call(scale, absoluteValue)) {
```
Comment (trend-albert-shala) [inline packages/styled-system/src/utils/transforms.js:122]:
```suggestion
    if (isNonNegative || !Object.hasOwn.call(scale, absoluteValue)) {
```

File: packages/styled-system/src/utils/transforms.js [hunk 2]
```diff
@@ -1,35 +1,57 @@
...
 
-  if (useCSSVariables) {
-    const contextScale = context?.scale;
+  return `-${n}`;
+};
+
+export const getter = (scale, value, options) => {
+  const prefix = options?.props?.theme?.config?.prefix; // defaults to 'tonic'
+  const useCSSVariables = !!(options?.props?.theme?.config?.useCSSVariables); // defaults to false
+  const cssVariableMap = options?.props?.theme?.__cssVariableMap;
```
Comment (trend-albert-shala) [inline packages/styled-system/src/utils/transforms.js]:
```suggestion
  const { config, __cssVariableMap } =  options?.props?.theme
  const prefix = config?.prefix; // defaults to 'tonic'
  const useCSSVariables = !!(config?.useCSSVariables); // defaults to false
  const cssVariableMap = __cssVariableMap;
```

File: packages/styled-system/src/utils/transforms.js [hunk 3]
```diff
@@ -1,35 +1,57 @@
...
+  const result = get(scale, value);
+
+  if (result !== undefined && useCSSVariables) {
```
Comment (trend-albert-shala) [inline packages/styled-system/src/utils/transforms.js:37]:
```suggestion
  if (result && useCSSVariables) {
```

File: packages/styled-system/src/utils/transforms.js [hunk 4]
```diff
@@ -57,16 +79,15 @@ export const positiveOrNegative = (scale, value, options) => {
...
-      return getter(scale, value, options);
-    }
     const absoluteValue = (value.startsWith('+') || value.startsWith('-')) ? value.slice(1) : value;
-    const n = getter(scale, absoluteValue, options);
-    if (typeof n === 'string') {
-      return `calc(${n} * -1)`;
+    const isNonNegative = !value.startsWith('-');
+
+    // Return the result if the value is non-negative or if the scale object does not contain the absolute value
+    if (isNonNegative || !Object.prototype.hasOwnProperty.call(scale, absoluteValue)) {
```
Comment (trend-albert-shala) [inline packages/styled-system/src/utils/transforms.js:87]:
```suggestion
    if (isNonNegative || !!Object.hasOwn.call(scale, absoluteValue)) {
```

**Review by trend-albert-shala — COMMENTED** [review]
Leaving a few suggestions, but overall looks good

File: packages/styled-system/src/utils/transforms.js (hunk 1 above)
Comment (cheton) [reply packages/styled-system/src/utils/transforms.js:122]: I have been considering whether to use `Object.hasOwn` or `Object.prototype.hasOwnProperty.call`.

https://caniuse.com/mdn-javascript_builtins_object_hasown
image

`Object.hasOwn` was introduced around 2021. Since it's still quite new and the `styled-system` package acts as a common library rather than an app, I might choose to use the legacy `Object.prototype.hasOwnProperty.call`  for now to ensure that the library functions correctly in older environments.

File: packages/styled-system/src/utils/transforms.js (hunk 3 above)
Comment (cheton) [reply packages/styled-system/src/utils/transforms.js:37]: If the `result` is 0 and we don't compare it with `undefined`, it won't have a chance to get into the CSS variable replacement. Here is a case that failed the test:

image

File: packages/styled-system/src/utils/transforms.js (hunk 2 above)
Comment (cheton) [reply packages/styled-system/src/utils/transforms.js]: revised in https://github.com/trendmicro-frontend/tonic-ui/pull/869/commits/788cc15cbe779a12e5c5557e9045f6c76eea5404

File: packages/styled-system/src/utils/transforms.js (hunk 1 above)
Comment (trend-albert-shala) [reply packages/styled-system/src/utils/transforms.js:122]: Got it, thanks for sharing that context, and i think it's worthwhile to explore alternative options to polyfil new JS features for older browser, just so you can get access to new and improved features

File: packages/styled-system/src/utils/transforms.js (hunk 3 above)
Comment (trend-albert-shala) [reply packages/styled-system/src/utils/transforms.js:37]: I see, thanks for testing this out.

**Comment by cheton** [comment]
Fixed in [1.29.3](https://github.com/trendmicro-frontend/tonic-ui/releases/tag/%40tonic-ui%2Freact%401.29.3) and [2.0.1](https://github.com/trendmicro-frontend/tonic-ui/releases/tag/%40tonic-ui%2Freact%402.0.1)
