### PR TITLE
fix: fixes an issue that cannot locate tooltip trigger if explicitly set the `isOpen` prop

### LINKED ISSUE #396: tooltip issue
tooltip can not show correctly when set defaultIsOpen true.
image

### PR DESCRIPTION
**Pull request by cheton**
Demo: https://trendmicro-frontend.github.io/tonic-ui-demo/react/pr-408/tooltip

See #410 for a similar issue on popover

## Description

The tooltip cannot locate the trigger if explicitly set the `isOpen` prop.

### Steps to reproduce

1. Go to https://trendmicro-frontend.github.io/tonic-ui/react/0.23.0/tooltip
2. Add the `isOpen` prop to a `Tooltip` component.
3. Inline styles are not available on the tooltip trigger
 image

### Expected result

image

image

## What's Changed

* Use `isHydrated` state to check whether it is the initial render for SSR-friendly.
* Remove `aria-label`, `defaultIsOpen`, `shouldWrapChildren` props.
* You can use function as children to render the tooltip trigger (anchor) if you don't want it to be wrapped with a `Box` component:
  ```jsx
  <Tooltip label="tooltip label">
    {({ getTooltipTriggerProps }) => {
      return (
        <Button {...getTooltipTriggerProps()}>
          Tooltip Trigger
        </Button>
      );
    }}
  </Tooltip>
  ```
  image

### CODE REVIEW

File: packages/react/src/Tooltip/index.js [hunk 1]
```diff
@@ -70,86 +94,64 @@ const Tooltip = ({
...
-      onMouseEnter: wrapEvent(child.props.onMouseEnter, handleOpen),
-      onMouseLeave: wrapEvent(child.props.onMouseLeave, handleClose),
-      onClick: wrapEvent(child.props.onClick, handleClick),
-      onFocus: wrapEvent(child.props.onFocus, handleOpen),
-      onBlur: wrapEvent(child.props.onBlur, handleClose),
-    });
-  }
+      display: 'inline-block',
+      role: 'presentation',
+      tabIndex: '0',
```
Comment (cheton) [inline packages/react/src/Tooltip/index.js]: remove `tabIndex`

Comment (cheton) [reply packages/react/src/Tooltip/index.js]: fixed in b70a2a2f621071a283dacdbd9fcae755e73760b6

**Review by tinaClin — APPROVED** [review]
