### PR TITLE
fix(react/OverflowTooltip): show the tooltip only when the string is truncated and the `disabled` prop is not true

### LINKED ISSUE #912: [OverflowTooltip] This will always show the tooltip if the disabled prop is false, even if the string is not truncated
## Issue

This will always show the tooltip if the disabled prop is false, even if the string is not truncated.

### v2.0.3
image

## Expection

The tooltip should be shown only if the string is truncated when the disabled prop is false.

### PR DESCRIPTION
**Pull request by tinaClin**
The tooltip should be shown only if the string is truncated when the disabled prop is false.

Issue: https://github.com/trendmicro-frontend/tonic-ui/issues/912

### CODE REVIEW

File: packages/react/src/tooltip/OverflowTooltip.js [hunk 1]
```diff
@@ -61,7 +62,7 @@ const OverflowTooltip = forwardRef((
   useEventListener(eventTargetFn, 'mouseleave', onMouseLeave);
 
   const tooltipProps = {
-    disabled: !isOverflow,
+    disabled: disabled || !isOverflow,
```
Comment (cheton) [inline packages/react/src/tooltip/OverflowTooltip.js]: Here is the summary of the changes:
* If `disabled` is `true`, the `disabled` property in `tooltipProps` will be set to `true`, regardless of `isOverflow`.
* If `disabled` is `false` or a nullish value, the `disabled` property in `tooltipProps` will depend on `isOverflow`:
  * When there is no overflow, the tooltip will be disabled (the `disabled` prop will be `true`).
  * When there is overflow, the tooltip will remain enabled (the `disabled` prop will be `false`).
  
@tinaClin Could you please review to ensure this is correct?

Comment (tinaClin) [reply packages/react/src/tooltip/OverflowTooltip.js]: Yes, it is. Thank you for your summary.

Comment (cheton) [reply packages/react/src/tooltip/OverflowTooltip.js]: I modified the code in the commit (https://github.com/trendmicro-frontend/tonic-ui/pull/913/commits/670cb962fc8faa56a49db001a3598f8e4720fe8f) to conditionally set the `disabled` prop based on the overflow state. As for the `nextToCursor` prop, there's no need to check the overflow state. Did you notice any issues with this update?

```js
const tooltipProps = {
  // The `disabled` prop is set to `true` if there is no overflow
  disabled: isOverflow ? disabledProp : true,
  nextToCursor: nextToCursorProp,
  offset: offsetProp,
  placement: placementProp,
};
```

**Review by cheton — APPROVED** [review]
